namespace EmuWarface.Game.Enums
{
    public enum UserInvitationStatus
    {
        Accepted,
        Rejected,
        AutoReject,
        Pending,
        Duplicate,
        UserOffline,
        InvalidState,
        LimitReached,
        ServiceError,
        Expired,
        DuplicateFollow,
        TargetInvalid,
        MissionRestriction,
        RankRestriction,
        FullRoom,
        Banned,
        BannedForLeave,
        BuilTypeMismatch,
        PrivateRoom,
        NotInClan,
        NotParticipateToClanWar,
        ClassRestricted,
        BuildVersionMismatch,
        ItemNotAvailable,
        NotParticipateInRankedGame
    }
}
